apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: default
type: Opaque
stringData:
  JWT_SECRET: "your-super-secret-jwt-key"
  DB_PASSWORD: "secret"
  GOOGLE_CLIENT_ID: "969716305726-r3v0ue477522soi6sta45qh62gnstei4.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET: "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"
  AWS_ACCESS_KEY_ID: "minioadmin"
  AWS_SECRET_ACCESS_KEY: "minioadmin"
